[workspace]
members = ["crates/*"]
exclude = ["crates/cranelift-codegen/meta", "crates/cranelift-isle"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
dtb-parser = { path = "./crates/dtb-parser" }
kernel = { path = "_kernel" }
sbicall = { path = "./crates/sbicall" }
uart-16550 = { path = "./crates/uart-16550" }
wasmparser = { path = "./crates/wasmparser" }
cranelift-wasm = { path = "./crates/cranelift-wasm" }
cranelift-bforest = { path = "./crates/cranelift-bforest" }
cranelift-codegen = { path = "./crates/cranelift-codegen" }
cranelift-entity = { path = "./crates/cranelift-entity" }
cranelift-frontend = { path = "./crates/cranelift-frontend" }
fxhash = { path = "./crates/fxhash" }
gimli = { path = "./crates/gimli" }
bitflags = "2.4.1"
log = "0.4.20"
riscv = "0.11.0"
cfg-if = "1.0.0"
hashbrown = { version = "0.14.3", features = ["nightly"] }
onlyerror = { version = "0.1.3", default-features = false }
smallvec = "2.0.0-alpha.3"
target-lexicon = { version = "0.12.13", default-features = false }
bumpalo = "3.14.0"
regalloc2 = { version = "0.9.3", default-features = false }
spin = "0.9.8"
linked_list_allocator = "0.10.5"

[profile.dev]
#opt-level = 1

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true
split-debuginfo = "packed"

[profile.test]
split-debuginfo = "packed"