[workspace]
members = ["build/*", "libs/*", "kernel", "loader", "loader/api", "loader/api/macros", "libs/ktest/macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]
license = "MIT"

[workspace.dependencies]
dtb-parser = { path = "libs/dtb-parser" }
uart-16550 = { path = "libs/uart-16550" }
vmm = { path = "libs/vmm" }
fxhash = { path = "libs/fxhash" }
gimli = { path = "libs/gimli" }
loader-api = { path = "loader/api" }
kstd = { path = "libs/kstd" }
ktest = { path = "libs/ktest" }

onlyerror = { version = "0.1.4", default-features = false }
log = "0.4.21"
bitflags = "2.5.0"
cfg-if = "1.0.0"
linked_list_allocator = "0.10.5"
arrayvec = { version = "0.7.4", default-features = false }
ed25519-dalek = { version = "2.1.1", default-features = false }
object = { version = "0.36.0", default-features = false }
lz4_flex = { version = "0.11", default-features = false }
lock_api = "0.4.12"

# cranelift dependencies
hashbrown = { version = "0.14.3", features = ["nightly"] }
cranelift-wasm = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core"] }
cranelift-codegen = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core", "host-arch"] }
cranelift-frontend = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core"] }
cranelift-entity = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false }
target-lexicon = { version = "0.12.13", default-features = false }

# build dependencies
serde = { version = "1.0.199", default-features = false, features = ["derive"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
anstyle = "1.0.6"
cargo_metadata = "0.18.1"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
toml = "0.8.12"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true
split-debuginfo = "packed"

[profile.dev.package.ed25519-dalek]
opt-level = 3
