[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
onlyerror = { version = "0.1.3", default-features = false }
bitflags = "2.4.1"
log = "0.4.20"
riscv = "0.10.1"