[workspace]
members = ["build/*", "libs/*", "kernel", "loader"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]

[workspace.dependencies]
dtb-parser = { path = "libs/dtb-parser" }
uart-16550 = { path = "libs/uart-16550" }
riscv = { path = "libs/riscv" }
vmm = { path = "libs/vmm" }
cranelift-bforest = { path = "libs/cranelift-bforest" }
cranelift-codegen = { path = "libs/cranelift-codegen" }
cranelift-entity = { path = "libs/cranelift-entity" }
cranelift-frontend = { path = "libs/cranelift-frontend" }
cranelift-wasm = { path = "libs/cranelift-wasm" }
fxhash = { path = "libs/fxhash" }
gimli = { path = "libs/gimli" }
wasmparser = { path = "libs/wasmparser" }

onlyerror = { version = "0.1.4", default-features = false }
log = "0.4.21"
bitflags = "2.5.0"
cfg-if = "1.0.0"
spin = "0.9.8"
linked_list_allocator = "0.10.5"
arrayvec = { version = "0.7.4", default-features = false }
riscv = "0.11.1"
ed25519-dalek = { version = "2.1.1", default-features = false }

# cranelift dependencies
hashbrown = { version = "0.14.3", features = ["nightly"] }
target-lexicon = { version = "0.12.14", default-features = false }
bumpalo = "3.15.4"
regalloc2 = { version = "0.9.3", default-features = false }
smallvec = "2.0.0-alpha.5"

# build dependencies
rand_core = { version = "0.6.4", features = ["getrandom"] }
cranelift-isle = { path = "build/cranelift-isle" }
build-config = { path = "build/config" }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
anstyle = "1.0.6"
cargo_metadata = "0.18.1"
anyhow = "1.0.81"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
toml = "0.8.12"
similar = "2.5.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true
split-debuginfo = "packed"
