[workspace]
members = ["build/*", "libs/*", "kernel", "loader"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]
license = "MIT"

[workspace.dependencies]
dtb-parser = { path = "libs/dtb-parser" }
uart-16550 = { path = "libs/uart-16550" }
riscv = { path = "libs/riscv" }
vmm = { path = "libs/vmm" }
sync = { path = "libs/sync" }
fxhash = { path = "libs/fxhash" }
gimli = { path = "libs/gimli" }

onlyerror = { version = "0.1.4", default-features = false }
log = "0.4.21"
bitflags = "2.5.0"
cfg-if = "1.0.0"
linked_list_allocator = "0.10.5"
arrayvec = { version = "0.7.4", default-features = false }
ed25519-dalek = { version = "2.1.1", default-features = false }

# cranelift dependencies
hashbrown = { version = "0.14.3", features = ["nightly"] }
cranelift-wasm = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core"] }
cranelift-codegen = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core", "host-arch"] }
cranelift-frontend = { git = "https://github.com/JonasKruckenberg/wasmtime", branch = "no_std", default-features = false, features = ["core"] }
target-lexicon = { version = "0.12.13", default-features = false }

# build dependencies
rand_core = { version = "0.6.4", features = ["getrandom"] }
cranelift-isle = { path = "build/cranelift-isle" }
build-config = { path = "build/config" }
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
anstyle = "1.0.6"
cargo_metadata = "0.18.1"
anyhow = "1.0.82"
serde = { version = "1.0.198", default-features = false, features = ["derive"] }
toml = "0.8.12"
similar = "2.5.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true
split-debuginfo = "packed"

[profile.dev.package.ed25519-dalek]
opt-level = 3
