[workspace]
members = ["build/*", "kernel", "libs/*", "loader"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jonas Kruckenberg <iterpre@protonmail.com>"]

[workspace.dependencies]
dtb-parser = { path = "libs/dtb-parser" }
uart-16550 = { path = "libs/uart-16550" }
sbicall = { path = "libs/sbicall" }
vmm = { path = "libs/vmm" }
semihosting-logger = { path = "libs/semihosting-logger" }
cranelift-bforest = { path = "libs/cranelift-bforest" }
cranelift-codegen = { path = "libs/cranelift-codegen" }
cranelift-entity = { path = "libs/cranelift-entity" }
cranelift-frontend = { path = "libs/cranelift-frontend" }
cranelift-wasm = { path = "libs/cranelift-was" }
fxhash = { path = "libs/fxhash" }
gimli = { path = "libs/gimli" }
wasmparser = { path = "libs/wasmparser" }

onlyerror = { version = "0.1.3", default-features = false }
log = "0.4.20"
bitflags = "2.4.1"
cfg-if = "1.0.0"
spin = "0.9.8"
linked_list_allocator = "0.10.5"
arrayvec = { version = "0.7.4", default-features = false }
lz4_flex = { version = "0.11.3", default-features = false }
hashbrown = { version = "0.14.3", features = ["nightly"] }
target-lexicon = { version = "0.12.13", default-features = false }
bumpalo = "3.14.0"
regalloc2 = { version = "0.9.3", default-features = false }
smallvec = "2.0.0-alpha.4"
qemu-exit = "3.0.2"

riscv = "0.11.0"
riscv-semihosting = "0.1.0"


cranelift-isle = { path = "build/cranelift-isle" }
build-config = { path = "build/config" }
clap = { version = "4.5.0", features = ["derive"] }
env_logger = "0.11.2"
anstyle = "1.0.6"
cargo_metadata = "0.18.1"
anyhow = "1.0.79"
serde = { version = "1.0.196", default-features = false, features = ["derive"] }
toml = "0.8.10"
ron = "0.8.1"
quote = "1.0.35"
proc-macro2 = "1.0.78"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
overflow-checks = true
split-debuginfo = "packed"

[profile.dev.package.lz4_flex]
opt-level = 3
