[package]
name = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cfg-if.workspace = true
log.workspace = true
spin.workspace = true
vmm.workspace = true

[build-dependencies]
build-config.workspace = true
anyhow.workspace = true
