[package]
name = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
arrayvec.workspace = true
cfg-if.workspace = true
dtb-parser.workspace = true
log.workspace = true
sbicall.workspace = true
spin.workspace = true
uart-16550.workspace = true
vmm.workspace = true

[build-dependencies]
ron.workspace = true
anyhow.workspace = true
quote.workspace = true
proc-macro2.workspace = true
build-config.workspace = true
