[package]
name = "kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vmm.workspace = true
dtb-parser.workspace = true
uart-16550.workspace = true
sync.workspace = true
riscv.workspace = true

cfg-if.workspace = true
log.workspace = true
linked_list_allocator.workspace = true
arrayvec.workspace = true
cranelift-wasm.workspace = true
cranelift-codegen.workspace = true
cranelift-frontend.workspace = true
target-lexicon.workspace = true
#gimli = { workspace = true, features = ["read"] }
onlyerror.workspace = true

hdrhistogram = { workspace = true, optional = true, features = ["core", "serialization"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true, features = ["alloc"] }

[build-dependencies]
build-config.workspace = true
anyhow.workspace = true

[features]
track-allocations = ["hdrhistogram", "serde", "serde_json"]