
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.wasmtime]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[policy.cranelift-bforest]
audit-as-crates-io = true

[policy.cranelift-codegen]
audit-as-crates-io = true

[policy.cranelift-codegen-meta]
audit-as-crates-io = true

[policy.cranelift-codegen-shared]
audit-as-crates-io = true

[policy.cranelift-control]
audit-as-crates-io = true

[policy.cranelift-entity]
audit-as-crates-io = true

[policy.cranelift-frontend]
audit-as-crates-io = true

[policy.cranelift-isle]
audit-as-crates-io = true

[policy.cranelift-wasm]
audit-as-crates-io = true

[policy.gimli]
audit-as-crates-io = true

[policy.hdrhistogram]
audit-as-crates-io = true

[policy.wasmtime-types]
audit-as-crates-io = true

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.18"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.14"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.83"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.7"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.16.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.1.6"
criteria = "safe-to-deploy"

[[exemptions.cargo-platform]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.cargo_metadata]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.cassowary]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.4"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.2"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.4"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.cranelift-bforest]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen-meta]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-codegen-shared]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-control]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-entity]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-frontend]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-isle]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.cranelift-wasm]]
version = "0.108.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.crossterm]]
version = "0.27.0"
criteria = "safe-to-deploy"

[[exemptions.crossterm_winapi]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.env_filter]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.fiat-crypto]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hdrhistogram]]
version = "7.5.4@git:97de23c32f23c544a304d52d58068813f8563ac0"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.2.6"
criteria = "safe-to-deploy"

[[exemptions.indoc]]
version = "2.0.5"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.154"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.linked_list_allocator]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.lru]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.myn]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.onlyerror]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.platforms]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.82"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.36"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.ratatui]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.10.4"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustc-hash]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.16"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.200"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.200"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.116"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.signal-hook]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-mio]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.slice-group-by]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.spinning_top]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.stability]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.strum]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.strum_macros]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.61"
criteria = "safe-to-deploy"

[[exemptions.target-lexicon]]
version = "0.12.14"
criteria = "safe-to-deploy"

[[exemptions.test-assembler]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.60"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.60"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.22.12"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.value-bag]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasmtime-types]]
version = "21.0.0@git:e4a28bc9b49f4c3dc3b85b3b5e1ecbe81406f802"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.6.8"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.34"
criteria = "safe-to-deploy"
