[target.'cfg(all(target_arch = "riscv64", target_os="none"))']
runner = "cargo run --package bootimg-runner --"
rustflags = [
    "-C", "relocation-model=pie",
    "-C", "link-args=-zseparate-loadable-segments",
    "-C", "link-args=--image-base=0xffffffff80000000"
]
