[package]
name = "loader"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
loader-api.workspace = true
dtb-parser.workspace = true
vmm = { workspace = true, features = ["elf"] }
sync.workspace = true

cfg-if.workspace = true
arrayvec.workspace = true
log.workspace = true
lz4_flex.workspace = true
bitflags.workspace = true
ed25519-dalek = { workspace = true, features = ["fast"] }
linked_list_allocator.workspace = true
object = { workspace = true, features = ["read_core", "elf"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv.workspace = true
