[package]
name = "loader"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
arrayvec.workspace = true
cfg-if.workspace = true
dtb-parser.workspace = true
log.workspace = true
sbicall.workspace = true
spin.workspace = true
vmm.workspace = true
semihosting-logger = { workspace = true, optional = true }
lz4_flex = { workspace = true, features = ["safe-decode"] }
linked_list_allocator.workspace = true
bitflags.workspace = true

[build-dependencies]
ron.workspace = true
anyhow.workspace = true
quote.workspace = true
proc-macro2.workspace = true
build-config.workspace = true

[features]
# Enable semihosting-related features
# This will switch the logger from using the `sbi`-based system, to the `semihosting-logger`
# which will make the console output much more readable in QEMU.
# In the future this will also enable other functionality.
semihosting = ["dep:semihosting-logger"]
