[package]
name = "loader"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cfg-if.workspace = true
log.workspace = true
spin.workspace = true
vmm.workspace = true
arrayvec.workspace = true
dtb-parser.workspace = true
riscv.workspace = true
ed25519-dalek = { workspace = true, features = ["fast"] }
bitflags.workspace = true

[build-dependencies]
build-config.workspace = true
anyhow.workspace = true