name = "riscv64-virt" # Name of the configuration
version = "0.1.0" # Version of the configuration
target = "riscv64gc-unknown-none-elf" # Rust target triple to compile for
memory-mode = "Riscv64Sv39"
uart-baud-rate = 38400

[kernel]
stack-size-pages = 16 # Size of the per-hart stack in pages
log-level = "debug"

[bootloader]
stack-size-pages = 4 # Size of the per-hart stack in pages
log-level = "debug"