name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build book
        run: mdbook build manual
      - name: Deploy
        run: |
          git worktree add --orphan -B gh-pages gh-pages
          cp -r manual/book/ gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          git add -A
          git commit -m 'deploy new book'
          git push origin +gh-pages
